"""add_email_verification_codes

Revision ID: 09dbad68cd7e
Revises: 8b1850972073
Create Date: 2026-09-02 17:17:45.373032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dbad68cd7e'
down_revision: Union[str, None] = '8b1850972073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_verification_email', 'email_verification_codes', [sa.literal_column('lower(email)')], unique=False)
    op.create_index('idx_email_verification_hash', 'email_verification_codes', ['code_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email_verification_hash', table_name='email_verification_codes')
    op.drop_index('idx_email_verification_email', table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
