"""add_auth_and_user_data_isolation

Revision ID: 8b1850972073
Revises: df6062071a5c
Create Date: 2026-08-31 19:38:28.037531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1850972073'
down_revision: Union[str, None] = 'df6062071a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_lower_unique', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('idx_users_google_id_unique', 'users', ['google_id'], unique=True, postgresql_where=sa.text('google_id IS NOT NULL'))
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_name_lower_unique', 'categories', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('idx_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('idx_categories_user_name_unique', 'categories', ['user_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_password_reset_tokens_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index('idx_password_reset_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'overall' AND category_id IS NULL) OR (scope = 'category' AND category_id IS NOT NULL)", name='check_budgets_category_id_scope_nullability'),
    sa.CheckConstraint("scope IN ('overall', 'category')", name='check_budgets_scope'),
    sa.CheckConstraint('limit_amount > 0', name='check_budgets_limit_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budgets_unique_user_category', 'budgets', ['user_id', 'scope', 'category_id', 'period_month'], unique=True, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index('idx_budgets_unique_user_overall', 'budgets', ['user_id', 'scope', 'period_month'], unique=True, postgresql_where=sa.text('category_id IS NULL'))
    op.create_index('idx_budgets_user_id', 'budgets', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_mode IN ('cash', 'card', 'upi', 'other')", name='check_expenses_payment_mode'),
    sa.CheckConstraint('amount > 0', name='check_expenses_amount_positive'),
    sa.CheckConstraint('expense_date <= CURRENT_DATE', name='check_expenses_date_not_future'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_amount', 'expenses', ['amount'], unique=False)
    op.create_index('idx_expenses_category_id', 'expenses', ['category_id'], unique=False)
    op.create_index('idx_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('idx_expenses_title_notes', 'expenses', ['title', 'notes'], unique=False)
    op.create_index('idx_expenses_user_amount', 'expenses', ['user_id', 'amount'], unique=False)
    op.create_index('idx_expenses_user_category', 'expenses', ['user_id', 'category_id'], unique=False)
    op.create_index('idx_expenses_user_date', 'expenses', ['user_id', 'expense_date'], unique=False)
    op.create_index('idx_expenses_user_id', 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_user_id', table_name='expenses')
    op.drop_index('idx_expenses_user_date', table_name='expenses')
    op.drop_index('idx_expenses_user_category', table_name='expenses')
    op.drop_index('idx_expenses_user_amount', table_name='expenses')
    op.drop_index('idx_expenses_title_notes', table_name='expenses')
    op.drop_index('idx_expenses_expense_date', table_name='expenses')
    op.drop_index('idx_expenses_category_id', table_name='expenses')
    op.drop_index('idx_expenses_amount', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('idx_budgets_user_id', table_name='budgets')
    op.drop_index('idx_budgets_unique_user_overall', table_name='budgets', postgresql_where=sa.text('category_id IS NULL'))
    op.drop_index('idx_budgets_unique_user_category', table_name='budgets', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_table('budgets')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_password_reset_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_categories_user_name_unique', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_categories_user_id', table_name='categories')
    op.drop_index('idx_categories_name_lower_unique', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_table('categories')
    op.drop_index('idx_users_google_id_unique', table_name='users', postgresql_where=sa.text('google_id IS NOT NULL'))
    op.drop_index('idx_users_email_lower_unique', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
