"""Initial schema

Revision ID: df6062071a5c
Revises: None
Create Date: 2026-08-26 17:42:18.374958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6062071a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_name_lower_unique', 'categories', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'overall' AND category_id IS NULL) OR (scope = 'category' AND category_id IS NOT NULL)", name='check_budgets_category_id_scope_nullability'),
    sa.CheckConstraint("scope IN ('overall', 'category')", name='check_budgets_scope'),
    sa.CheckConstraint('limit_amount > 0', name='check_budgets_limit_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budgets_unique_category', 'budgets', ['scope', 'category_id', 'period_month'], unique=True, postgresql_where=sa.text('category_id IS NOT NULL'))
    op.create_index('idx_budgets_unique_overall', 'budgets', ['scope', 'period_month'], unique=True, postgresql_where=sa.text('category_id IS NULL'))
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_mode IN ('cash', 'card', 'upi', 'other')", name='check_expenses_payment_mode'),
    sa.CheckConstraint('amount > 0', name='check_expenses_amount_positive'),
    sa.CheckConstraint('expense_date <= CURRENT_DATE', name='check_expenses_date_not_future'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_amount', 'expenses', ['amount'], unique=False)
    op.create_index('idx_expenses_category_id', 'expenses', ['category_id'], unique=False)
    op.create_index('idx_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('idx_expenses_title_notes', 'expenses', ['title', 'notes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_title_notes', table_name='expenses')
    op.drop_index('idx_expenses_expense_date', table_name='expenses')
    op.drop_index('idx_expenses_category_id', table_name='expenses')
    op.drop_index('idx_expenses_amount', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('idx_budgets_unique_overall', table_name='budgets', postgresql_where=sa.text('category_id IS NULL'))
    op.drop_index('idx_budgets_unique_category', table_name='budgets', postgresql_where=sa.text('category_id IS NOT NULL'))
    op.drop_table('budgets')
    op.drop_index('idx_categories_name_lower_unique', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
